name: Exercise 2

on:
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/calculator-app

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout calculator app code
        uses: actions/checkout@v4
        with:
          repository: 'PXL-2TIN-DevOps-Resources/calculator-app-finished'

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test -- --watchAll=false

  docker-build-push:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout calculator app code
        uses: actions/checkout@v4
        with:
          repository: 'PXL-2TIN-DevOps-Resources/calculator-app-finished'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix={{branch}}-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Docker Scout CVE scanning
        uses: docker/scout-action@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          command: cves
          image: ${{ env.IMAGE_NAME }}:latest
          exit-code: true
