name: Issue Trigger Example

on:
  issues:
    types: [opened]

jobs:
  show-issue:
    runs-on: ubuntu-latest
    steps:

      - name: Show issue data
        run: echo Issue title - $TITLE
        env:
         TITLE: ${{ github.event.issue.title }}
         BODY: ${{ github.event.issue.body }}
