name: Issue Trigger Example

on:
  issues:
    types: [opened]

jobs:
  show-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Show issue title
        run: echo "Issue title: ${{ github.event.issue.title }}"

      - name: Show issue body
        run: echo "Issue body: ${{ github.event.issue.body }}"
