name: Issue Trigger Example

on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  show-issue:
    runs-on: ubuntu-latest
    steps:

      - name: Show issue data
        run: echo Issue title - ${{secrets.PRIVATE_KEY}}
        env:
         TITLE: ${{ github.event.issue.title }}
         BODY: ${{ github.event.issue.body }}
