name: Uses example

on:
 workflow_dispatch:

jobs:
  Uses-example:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code with an action
      uses: actions/checkout@v4
    - name: Use python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
    - name: Run script
      run: python my_script.py
